### ISSUE TITLE
Decide on a license

### ISSUE THREAD

**Issue by yupferris** [yupferris/rustendo64#2]
My go-to is BSD2

**Comment by yupferris** [comment]
Would BSD2 be ok with you @zorend ? Asking since you did have a contribution :)

**Comment by emoon** [comment]
I have noticed that most Rust projects are dual MIT/Apache 2.0 licensed but you choice of course :)

**Comment by Dr-Emann** [comment]
Rust itself, and most rust projects chose to licence under dual MIT/Apache-2.0. See [here](https://github.com/iron/params/issues/7) for some reasoning behind this.

**Comment by oussama** [comment]
Hahaha, that's very thoughtful of you, thanks. Whatever you think is best go for it :)

**Comment by yupferris** [comment]
I've also noticed most of the Rust ecosystem uses dual MIT/Apache 2.0. After looking at @Dr-Emann 's link, I realize that BSD2 would have the same issues as _just_ using MIT (they're roughly equivalent licenses as far as I'm concerned), so dual BSD2/Apache 2.0 would also make sense, but in that case, why not conform a bit and use dual MIT/Apache 2.0 like the rest of the ecosystem?

So yeah, dual MIT/Apache 2.0 is looking like the best option currently.

**Comment by emoon** [comment]
:+1:
