### ISSUE TITLE
Public domain ROMs

### ISSUE THREAD

**Issue by DerekTurtleRoe** [yupferris/rustendo64#23]
So I saw you are struggling to find clean links to ROMs that are legal to download and don't contain anything else.

First of all, I have probably every available public domain/demo/homebrew ROM there is, so if you need any just let me know and I will send you any you want (or all of them, I guess).

But, I found a few places to get N64 PD ROMs legally and that are places you can trust.

http://www.pouet.net/prodlist.php?platform[0]=Nintendo+64&page=1

This place holds many demo ROMs made by N64 scene coders. Many of which I recommend for an interesting and entertaining experience at the very least.

http://www.zophar.net/pdroms/n64.html

A couple of ROMs that are pretty rare otherwise.

http://pdroms.de/news/nintendo64/

Many ROMs that aren't distributed by other websites, but it is mainly ScummVM releases.

http://micro-64.com/features/aafeatures.shtml

A few rarer, harder to come by ROMs, as well as a fairly good source of info on various unreleased games and homebrew releases.

Anyway, I thought I was going to add it to the README for you, but I figured you might want to look them over or try them before you did that. I also didn't want to go about messing with your project without your permission.

I contribute to CEN64, Project64, Mupen64Plus, and have a pretty good understanding of the 1964 and Mupen64 emulator as well. Feel free to use me as a resource if you want. I will help any way I can. I also know some of the people in the N64 community too, so even if I didn't know, I might know somebody who does!

Anyway, if you would like me to do a PR just say the word, and I will do as you ask.

Sorry for the wall of text. :smile:

**Comment by yupferris** [comment]
Hey, thanks so much for this! As you can tell, I've tried to keep myself fairly in-the-dark about most of the n64 emulation scene so that I don't miss anything in the learning process on stream. So, this is _extremely_ helpful!

Re pouet, [I'm actually an avid demoscener](http://www.pouet.net/user.php?who=16820&show=credits), and that's the one resource I seem to have forgotten to put in the readme myself. Nice!

Re zophar, I had no idea they had a section of public domain ROM's. Thanks for the tip!

I've never heard of the other resources, but I took a quick skim; these are great! And no worries about the wall of text. It's at least a pretty interesting wall :D

Anyways, I'd actually love for you to make a PR and put these in the readme. You can remove the little TODO note there while you're at it, hehe. Should be plenty here to fill that list out :) I'm trying to make a habit of going over and accepting PR's at the beginning of each stream, and would be perfect for that.

In terms of using you as a resource, my first question would be, which of all of these ROM's would you recommend we try to get running first?

**Comment by DerekTurtleRoe** [comment]
@yupferris I will create the PR after I am done writing this comment. :smile: 

Some interesting ROMs are Pong by Oman, Nacho64 by SPLiT, Twintris by Twinsen, 1964 demo by steb, the Mupen64Plus test ROM, the MGC 2011 ROM (I know, I'm saying it is a good test of whether your emulator is actually any good or not), Funnelcube by marshallh, and probably some input testing ROM. That way you know your analog stick values are correct. And having buttons correct is nice, too. :smiley: 

By the way, the MGC 2011 ROM can be run in Project64, but due to CPU bugs it de-syncs and the music gets way off. The frame rate isn't very good either. But it does run. I think TJ just got CEN64 to run MGC 2011 as well. :smile: Yay, progress.

If you can't find any of these ROMs, I would be more than happy to send them to you. There aren't that many public domain N64 ROMs (not a lot of interest in the N64 likely due to hardware complexity and development challenges), so I could probably compress all of them and send them to you fairly easily.

Anyway, thanks for starting this super interesting project and good luck!

EDIT: By the way, you might want to know that many PD ROMs require a controller to fully function. Just be aware of that when you start messing around with them. If you can get them to run though, some start automatically or just have debug and test stuff when you hit buttons or whatever.

**Comment by DerekTurtleRoe** [comment]
@yupferris I just remembered there are some N64 test ROMs you might find useful. They are to test individual components of the N64, like specific CPU instructions and stuff. Here is the link to the GitHub page:

https://github.com/PeterLemon/N64

I will add them to the PR in a minute.

Another ROM is the "View N64 Test ROM" which is another public domain ROM. I am having a hard time finding reputable links to the public domain ROMs, so maybe I can create a repository or something? I don't know, I will have to explore my options.

**Comment by yupferris** [comment]
Great stuff! Those test roms should be super helpful. Also a repo of public domain roms sounds really nice; not sure how you're supposed to "license" that sort of thing on github, or if that's even an issue?

**Comment by DerekTurtleRoe** [comment]
@yupferris Considering most of them are from the early 90's and made by people no longer in the scene, I think it should mostly be OK. But also, there aren't any official places to download them anyway, so I don't see why it would be a problem. I could add a small bit of text that says I will take it down if the original developer wishes it  and has a website or something.

Schibo (developer of 1964js) has a few in his repository, although those are for use in a JavaScript N64 emulator.

Let me setup a repository, I think this is a good idea. You should be able to access the ROMs without having to go to a sketchy website.

**Comment by yupferris** [comment]
Sounds great to me!

**Comment by DerekTurtleRoe** [comment]
@yupferris Here you go:

https://github.com/vgturtle127/N64-PD-ROMS

Be sure to act real surprised. :wink:

**Comment by yupferris** [comment]
holy balls that list is extensive!! Awesome stuff, thanks again!!

**Comment by juggle-tux** [comment]
@vgturtle127 +1

**Comment by DerekTurtleRoe** [comment]
@yupferris I may have more to add, actually. :smiley: 

Thanks, guys. I will have a lot more repositories and interesting stuff coming in the future. :wink:

**Comment by yupferris** [comment]
@vgturtle127 sweet! Did you get my email about certain other ROM's as well? XD

**Comment by DerekTurtleRoe** [comment]
@yupferris I will take a look at it now. I am also considering another repo with all the documentation in it, mostly so people have a single location with all the docs in it. :wink:

**Comment by yupferris** [comment]
you mean like this one? https://github.com/mikeryan/n64dev

**Comment by DerekTurtleRoe** [comment]
@yupferris Yeah, but more complete. No offense to Mike, obviously. It's just that he doesn't have every doc that is available. :wink: 

Mike is pretty great, he really knows his stuff. :smile:

**Comment by yupferris** [comment]
Well I'm happy to link any repo that at least contains docs that are public domain more or less :)

**Comment by DerekTurtleRoe** [comment]
@yupferris Alright, I am organizing my N64 doc collection now. I have over 10GB of docs, but I already had most of it organized. It shouldn't take too long.

**Comment by yupferris** [comment]
Kickass! Please let me know if any are going to be in there that you know I shouldn't be looking at/showing on stream ;)

**Comment by DerekTurtleRoe** [comment]
@yupferris Well, I can't upload any of that stuff to GitHub, so it should all be stuff you can look at. :wink:

**Comment by yupferris** [comment]
Right, just have to say to make damn sure ;D
