### ISSUE TITLE
Install instructions

### ISSUE THREAD

**Issue by amilajack** [yupferris/rustendo64#58]
I'm new to rust. Install instructions would be very useful in the readme. Would they be just:

``` bash
cargo install
cargo build
cargo run
```

?

**Comment by yupferris** [comment]
More like

```
cargo run
```

given you have Rust installed, ofc. Given that's really the only instruction that's specific to this project (and technically every Rust project works the same way), is https://github.com/yupferris/rustendo64#building-and-running really insufficient?

**Comment by amilajack** [comment]
I did that and thought I was missing something because I got this output:

``` bash
➜  rustendo64 git:(master) cargo run
     Running `target/debug/rustendo64`
thread '<main>' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore/option.rs:326
note: Run with `RUST_BACKTRACE=1` for a backtrace.
error: Process didn't exit successfully: `target/debug/rustendo64` (exit code: 101)
```

**Comment by yupferris** [comment]
Right, that means it built correctly (yay!), but failed at runtime. You also need to specify a PIF ROM and cart ROM, e.g.

```
cargo run -- pif.bin cart.bin
```

So it's not install instructions that are necessary, but perhaps running instructions. Perhaps that can be clarified. For example, it might be worth mentioning that I can't distribute my PIF ROM (hence the mention of the SHA-1 for my file) so it's required that a "user" (hacker really; the emu is far too early for actual users haha) provide their own, plus the ROM. Also, documenting the usage feels a bit strange this early on as it's really just enough to get hacking with and not meant to be a very usable interface at all really. Anyways, something more than what's there might still be helpful.

**Comment by yupferris** [comment]
Also for the record all of this is covered in the videos atm, but I can understand that you might have just wanted to try running it without watching many many hours of development :)

**Comment by amilajack** [comment]
I've watched them but I had no idea what you were talking about 😂

**Comment by amilajack** [comment]
I come from a front-end background so rust is pretty new to me. I've been messing around with WebAssembly recently and was thinking of porting this to wasm.

**Comment by ryanhiebert** [comment]
That sounds like a pretty cool project! I haven't really been able to dig much into WebAssembly, or really figured out how I can write it yet. It was a while ago that I read the docs in the repository, and I don't know if they've improved enough for me to be able to figure out how to write it now. Do you have any links that you can point me to about how to write raw wasm?

**Comment by amilajack** [comment]
Thankfully, no one has to write wasm (that would be terrible). I've written a short blog post explaining how to compile to asm.js, a faster subset of javascript, (and eventually wasm): http://amilawelihinda.com/mad-science-with-webassembly/

**Comment by amilajack** [comment]
Also checkout https://github.com/AerialX/cargo-build.

**Comment by yupferris** [comment]
Reopening as I do think some run instructions could still be valuable.

**Comment by amilajack** [comment]
Thanks!

**Comment by amilajack** [comment]
@ryanhiebert check this out: http://jquesnelle.github.io/mupen64plus-ui-console/

**Comment by ryanhiebert** [comment]
@amilajack: (so long and...) Thanks for all the links!

**Comment by ryanhiebert** [comment]
@amilajack : Also, given that we're discussing this on a project that's writing a _compiled assembly interpreter_, I just might be the kind of person that _wants_ to write raw wasm. (I am)

**Comment by amilajack** [comment]
Ahh I see. Give it a go!

**Comment by ghost** [comment]
I'm currently watching your series, but would like to see the end result first. I've compiles the program with the release paramater, ran your program but I end up in a r64 console screen. Could you also add instructions on using the program, not only compiling it?

**Comment by yupferris** [comment]
I'm not sure what you mean by "end result".

If you mean "finished n64 emulator", currently, this is not a usable emulator. The r64 console screen is all it provides. The series is a live-coding journey for a project I've never done before, and the repo you see here is simply how far we've come.

However, if you simply want to run what's there already, it's possible to document the features of the console etc, but I feel it may be a bit too early to do so as it's not really useful yet. There may be an argument for documenting as we go so nothing gets missed, though, but if that were the case it still probably wouldn't be very useful documentation yet.

**Comment by ghost** [comment]
@yupferris Thanks for replying. As I said, I haven't finished the series yet and didn't know the emulator isn't finished yet. Maybe it's a good idea to mention that in the readme.

**Comment by yupferris** [comment]
I guess the "livecoding an n64 emulator in rust", along with "follow the process" etc wasn't clear enough then. :) I can perhaps clarify this later, but I'm going to close this issue for now as it's a bit invalid for the time being.
