### ISSUE TITLE
Did you mean Float 32?

### ISSUE THREAD

**Issue by bdirgo** [yupferris/rustendo64#61]
I'll admit I only saw the first stream, so excuse me if you already caught it. So, you read the registers of the CPU and the last registers, `reg_fcr*`, were "float 32" in the manual, and you wrote `u32` on the struct.

Not sure if you meant to do that, new to Rust and Emulation projects. Thanks for the stream!

**Comment by yupferris** [comment]
Hi!

The registers in question are floating-point _control_ registers (hence `fcr`, as opposed to `fpr` above in the source), so they're not floats themselves, only bitfields. `u32` is correct here.

Glad you enjoyed the stream!
